# -*- coding: utf-8 -*-
"""Global Air Pollution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0XkWqB3Qr1OzF4z2Ug1h06_95cBCpIw

# Phân tích dữ liệu chung
"""

import pandas as pd
file_path = "/content/global air pollution dataset.csv"
data = pd.read_csv(file_path)
data

data.info()

null_values = data.isnull().sum()

if null_values.sum() == 0:
    print("Bộ dữ liệu không chứa giá trị trống.")
else:
    print("Bộ dữ liệu chứa giá trị trống.")
    print("Số lượng giá trị trống trong mỗi cột:")
    print(null_values)

data['Country'] = data['Country'].fillna('Missing')
data['City'] = data['City'].fillna('Missing')
data

data.info()

duplicate_rows = data[data.duplicated()]

if duplicate_rows.empty:
    print("Bộ dữ liệu không chứa dòng trùng lặp.")
else:
    print("Bộ dữ liệu chứa dòng trùng lặp. Số lượng dòng trùng lặp:", len(duplicate_rows))
    print("Các dòng trùng lặp:")
    print(duplicate_rows)

data.describe()

data.nunique()

data['Country'].value_counts()

data['City'].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt
sns.pairplot(data)
plt.show()

"""# Chỉ số AQI"""

import pandas as pd
AQI_non_duplicated_country = data.loc[data.groupby('Country')['AQI Value'].idxmax()]
AQI_non_duplicated_country

import pandas as pd
import matplotlib.pyplot as plt
sorted_AQI_non_duplicated_country = AQI_non_duplicated_country.sort_values(by='AQI Value', ascending=False)
top_10_AQI_non_duplicated_country = sorted_AQI_non_duplicated_country.head(10)
plt.figure(figsize=(8, 6))
plt.barh(top_10_AQI_non_duplicated_country['Country'], top_10_AQI_non_duplicated_country['AQI Value'], color='#00ffff')
plt.xlabel('AQI Value')
plt.ylabel('Country')
plt.title('Top 10 Countries with Highest AQI Value')
plt.show()

import matplotlib.pyplot as plt
top_10_data = data.nlargest(10, 'AQI Value')
plt.figure(figsize=(10, 5))
plt.barh(top_10_data['Country'], top_10_data['AQI Value'], color='#fa8072')
plt.xlabel('AQI Value')
plt.ylabel('Country')
plt.title('Top 10 Countries with Highest AQI Value')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
sns.histplot(data['AQI Value'], bins=30, kde=True, color='#DDA0DD')
plt.xlabel('AQI Value')
plt.ylabel('Value')
plt.title('Histogram of AQI Value')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(14, 5))
sns.histplot(data['AQI Category'], color='lightpink', bins=10)
plt.title('Phân phối chỉ số AQI', fontsize=13)
plt.xlabel('Chỉ số AQI', fontsize=10)
plt.ylabel('Số lượng', fontsize=13)
plt.grid(True)

plt.show()

data['AQI Category'].value_counts()

import matplotlib.pyplot as plt
import pandas as pd
counts = data["AQI Category"].value_counts()
colors = ['#00ffff', '#faebd7', '#98fb98', '#ffb6c1', '#f08080', '#ee82ee' ]
plt.figure(figsize=(10, 5))
counts.plot(kind='pie', fontsize=10, colors=colors, autopct='%1.1f%%')
plt.xlabel("Category", weight="bold", color="#d8bfd8", fontsize=10, labelpad=20)
plt.axis('equal')
plt.legend(labels=counts.index, loc="best")
plt.show()

idx_max = AQI_non_duplicated_country[AQI_non_duplicated_country['AQI Value'] == data['AQI Value'].max()].index
max_rows = AQI_non_duplicated_country.loc[idx_max]
print("\nCác dòng có chỉ số AQI cao nhất:")
max_rows

idx_min = data['AQI Value'].idxmin()
min_aqi_value = data['AQI Value'].min()
min_rows = data[data['AQI Value'] == min_aqi_value]
print("\nCác dòng có chỉ số AQI thấp nhất:")
min_rows

"""# Khí CO"""

data['CO AQI Category'].value_counts()

import matplotlib.pyplot as plt
import pandas as pd
counts = data["CO AQI Category"].value_counts()
colors = ['#00ffff', '#faebd7', '#98fb98', '#ffb6c1', '#f08080', '#ee82ee' ]
plt.figure(figsize=(10, 5))
counts.plot(kind='pie', fontsize=10, colors=colors, autopct='%1.1f%%')
plt.xlabel("Category", weight="bold", color="#d8bfd8", fontsize=10, labelpad=20)
plt.axis('equal')
plt.legend(labels=counts.index, loc="best")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
sns.histplot(data['CO AQI Value'], bins=30, kde=True, color='#98fb98')
plt.xlabel('CO AQI Value')
plt.ylabel('Value')
plt.title('Histogram of CO AQI Value')
plt.show()

"""# Khí Ozone"""

data['Ozone AQI Category'].value_counts()

import matplotlib.pyplot as plt
import pandas as pd
counts = data["Ozone AQI Category"].value_counts()
colors = ['#00ffff', '#faebd7', '#98fb98', '#ffb6c1', '#f08080', '#ee82ee' ]
plt.figure(figsize=(10, 5))
counts.plot(kind='pie', fontsize=10, colors=colors, autopct='%1.1f%%')
plt.xlabel("Category", weight="bold", color="#d8bfd8", fontsize=10, labelpad=20)
plt.axis('equal')
plt.legend(labels=counts.index, loc="best")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
sns.histplot(data['Ozone AQI Value'], bins=30, kde=True, color='#FFB6C1')
plt.xlabel('Ozone AQI Value')
plt.ylabel('Value')
plt.title('Histogram of Ozone AQI Value')
plt.show()

"""# Khí NO2"""

data['NO2 AQI Category'].value_counts()

import matplotlib.pyplot as plt
import pandas as pd
counts = data["NO2 AQI Category"].value_counts()
colors = ['#00ffff', '#faebd7', '#98fb98', '#ffb6c1', '#f08080', '#ee82ee' ]
plt.figure(figsize=(10, 5))
counts.plot(kind='pie', fontsize=10, colors=colors, autopct='%1.1f%%')
plt.xlabel("Category", weight="bold", color="#d8bfd8", fontsize=10, labelpad=20)
plt.axis('equal')
plt.legend(labels=counts.index, loc="best")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
sns.histplot(data['NO2 AQI Value'], bins=30, kde=True, color='#FAFAD2')
plt.xlabel('NO2 AQI Value')
plt.ylabel('Value')
plt.title('Histogram of NO2 AQI Value')
plt.show()

"""# Chỉ số bụi mịn"""

data['PM2.5 AQI Category'].value_counts()

import matplotlib.pyplot as plt
import pandas as pd
counts = data["PM2.5 AQI Category"].value_counts()
colors = ['#00ffff', '#faebd7', '#98fb98', '#ffb6c1', '#f08080', '#ee82ee' ]
plt.figure(figsize=(10, 5))
counts.plot(kind='pie', fontsize=10, colors=colors, autopct='%1.1f%%')
plt.xlabel("Category", weight="bold", color="#d8bfd8", fontsize=10, labelpad=20)
plt.axis('equal')
plt.legend(labels=counts.index, loc="best")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
sns.histplot(data['PM2.5 AQI Value'], bins=30, kde=True, color='#33CCCC')
plt.xlabel('PM2.5 AQI Value')
plt.ylabel('Value')
plt.title('Histogram of PM2.5 AQI Value')
plt.show()

"""# Ô nhiễm không khí tại Việt Nam"""

data_vietnam = data[data['Country'] == 'Viet Nam']
print('Có Việt Nam trong bộ dữ liệu trên')

data_vietnam = data[data['Country'] == 'Viet Nam']
data_vietnam

data_vietnam.info()

data_vietnam.describe()

import matplotlib.pyplot as plt
import pandas as pd
counts = data_vietnam["AQI Category"].value_counts()
colors = ['#00ffff', '#faebd7', '#98fb98', '#ffb6c1', '#f08080', '#ee82ee' ]
plt.figure(figsize=(10, 5))
counts.plot(kind='pie', fontsize=10, colors=colors, autopct='%1.1f%%')
plt.xlabel("Loại AQI", weight="bold", color="#d8bfd8", fontsize=10, labelpad=20)
plt.axis('equal')
plt.legend(labels=counts.index, loc="best")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10, 5))
sns.histplot(data_vietnam['AQI Value'], bins=30, kde=True, color='#FFFF66')
plt.xlabel('AQI Value')
plt.ylabel('Value')
plt.title('Histogram of AQI Value')
plt.show()